import {
  assignGroupTeacherRequestSchema,
  assignTeacherRequestSchema,
  attendanceListResponseSchema,
  attendanceResponseSchema,
  classNoteListResponseSchema,
  classNoteResponseSchema,
  classSessionCalendarResponseSchema,
  classSessionListResponseSchema,
  classSessionResponseSchema,
  courseListResponseSchema,
  courseResponseSchema,
  createAttendanceRequestSchema,
  createClassNoteRequestSchema,
  createClassSessionRequestSchema,
  createCourseRequestSchema,
  createGroupRequestSchema,
  createScheduleOptionRequestSchema,
  createStudentRequestSchema,
  createTeacherRequestSchema,
  enrollStudentRequestSchema,
  enrollmentListResponseSchema,
  enrollmentResponseSchema,
  generateClassSessionsRequestSchema,
  generateClassSessionsResponseSchema,
  groupListResponseSchema,
  groupResponseSchema,
  groupTeacherResponseSchema,
  healthResponseSchema,
  loginRequestSchema,
  managePermissionRequestSchema,
  permissionListResponseSchema,
  permissionMutationResponseSchema,
  provisionAdministrativeRequestSchema,
  provisionDirectorRequestSchema,
  provisionStudentRequestSchema,
  provisionTeacherRequestSchema,
  scheduleOptionListResponseSchema,
  scheduleOptionResponseSchema,
  sessionResponseSchema,
  studentListResponseSchema,
  studentResponseSchema,
  teacherAssignmentResponseSchema,
  teacherListResponseSchema,
  teacherResponseSchema,
  updateAttendanceRequestSchema,
  updateClassNoteRequestSchema,
  updateClassSessionRequestSchema,
  updateCourseRequestSchema,
  updateGroupRequestSchema,
  updateScheduleOptionRequestSchema,
  updateStudentRequestSchema,
  updateTeacherRequestSchema,
} from '@academia/shared';
import { zodToOpenApiSchema } from './zod-json-schema.js';

const errorEnvelope = {
  type: 'object',
  required: ['error'],
  additionalProperties: false,
  properties: {
    error: {
      type: 'object',
      required: ['code', 'message'],
      additionalProperties: false,
      properties: {
        code: { type: 'string' },
        message: { type: 'string' },
      },
    },
  },
} as const;

export const openApiComponents = {
  securitySchemes: {
    sessionCookie: {
      type: 'apiKey',
      in: 'cookie',
      name: 'academia_session',
      description:
        'HttpOnly session cookie set by POST /auth/login. Swagger Try it out ' +
        'on the same origin (via /api/*) sends it automatically after login. ' +
        'Do not paste cookie values into Authorize — they are HttpOnly.',
    },
  },
  schemas: {
    HealthResponse: zodToOpenApiSchema(healthResponseSchema),
    LoginRequest: zodToOpenApiSchema(loginRequestSchema),
    SessionResponse: zodToOpenApiSchema(sessionResponseSchema),
    ProvisionDirectorRequest: zodToOpenApiSchema(provisionDirectorRequestSchema),
    ProvisionAdministrativeRequest: zodToOpenApiSchema(
      provisionAdministrativeRequestSchema,
    ),
    ProvisionTeacherRequest: zodToOpenApiSchema(provisionTeacherRequestSchema),
    ProvisionStudentRequest: zodToOpenApiSchema(provisionStudentRequestSchema),
    PermissionListResponse: zodToOpenApiSchema(permissionListResponseSchema),
    ManagePermissionRequest: zodToOpenApiSchema(managePermissionRequestSchema),
    PermissionMutationResponse: zodToOpenApiSchema(
      permissionMutationResponseSchema,
    ),
    StudentListResponse: zodToOpenApiSchema(studentListResponseSchema),
    StudentResponse: zodToOpenApiSchema(studentResponseSchema),
    CreateStudentRequest: zodToOpenApiSchema(createStudentRequestSchema),
    UpdateStudentRequest: zodToOpenApiSchema(updateStudentRequestSchema),
    TeacherListResponse: zodToOpenApiSchema(teacherListResponseSchema),
    TeacherResponse: zodToOpenApiSchema(teacherResponseSchema),
    CreateTeacherRequest: zodToOpenApiSchema(createTeacherRequestSchema),
    UpdateTeacherRequest: zodToOpenApiSchema(updateTeacherRequestSchema),
    TeacherAssignmentResponse: zodToOpenApiSchema(teacherAssignmentResponseSchema),
    AssignTeacherRequest: zodToOpenApiSchema(assignTeacherRequestSchema),
    CourseListResponse: zodToOpenApiSchema(courseListResponseSchema),
    CourseResponse: zodToOpenApiSchema(courseResponseSchema),
    CreateCourseRequest: zodToOpenApiSchema(createCourseRequestSchema),
    UpdateCourseRequest: zodToOpenApiSchema(updateCourseRequestSchema),
    GroupListResponse: zodToOpenApiSchema(groupListResponseSchema),
    GroupResponse: zodToOpenApiSchema(groupResponseSchema),
    CreateGroupRequest: zodToOpenApiSchema(createGroupRequestSchema),
    UpdateGroupRequest: zodToOpenApiSchema(updateGroupRequestSchema),
    GroupTeacherResponse: zodToOpenApiSchema(groupTeacherResponseSchema),
    AssignGroupTeacherRequest: zodToOpenApiSchema(assignGroupTeacherRequestSchema),
    EnrollmentListResponse: zodToOpenApiSchema(enrollmentListResponseSchema),
    EnrollmentResponse: zodToOpenApiSchema(enrollmentResponseSchema),
    EnrollStudentRequest: zodToOpenApiSchema(enrollStudentRequestSchema),
    ScheduleOptionListResponse: zodToOpenApiSchema(
      scheduleOptionListResponseSchema,
    ),
    ScheduleOptionResponse: zodToOpenApiSchema(scheduleOptionResponseSchema),
    CreateScheduleOptionRequest: zodToOpenApiSchema(
      createScheduleOptionRequestSchema,
    ),
    UpdateScheduleOptionRequest: zodToOpenApiSchema(
      updateScheduleOptionRequestSchema,
    ),
    ClassSessionListResponse: zodToOpenApiSchema(classSessionListResponseSchema),
    ClassSessionResponse: zodToOpenApiSchema(classSessionResponseSchema),
    CreateClassSessionRequest: zodToOpenApiSchema(createClassSessionRequestSchema),
    UpdateClassSessionRequest: zodToOpenApiSchema(updateClassSessionRequestSchema),
    GenerateClassSessionsRequest: zodToOpenApiSchema(
      generateClassSessionsRequestSchema,
    ),
    GenerateClassSessionsResponse: zodToOpenApiSchema(
      generateClassSessionsResponseSchema,
    ),
    ClassSessionCalendarResponse: zodToOpenApiSchema(
      classSessionCalendarResponseSchema,
    ),
    AttendanceListResponse: zodToOpenApiSchema(attendanceListResponseSchema),
    AttendanceResponse: zodToOpenApiSchema(attendanceResponseSchema),
    CreateAttendanceRequest: zodToOpenApiSchema(createAttendanceRequestSchema),
    UpdateAttendanceRequest: zodToOpenApiSchema(updateAttendanceRequestSchema),
    ClassNoteListResponse: zodToOpenApiSchema(classNoteListResponseSchema),
    ClassNoteResponse: zodToOpenApiSchema(classNoteResponseSchema),
    CreateClassNoteRequest: zodToOpenApiSchema(createClassNoteRequestSchema),
    UpdateClassNoteRequest: zodToOpenApiSchema(updateClassNoteRequestSchema),
    ErrorEnvelope: errorEnvelope,
  },
} as const;

export type OpenApiComponents = typeof openApiComponents;
